# Capítulo I – Estructura, lenguaje y sintaxis
## Análisis Cuantitativo con R: Matemáticas, Estadística y Econometría

**Autores del libro:** Daniel Liviano Solís · Maria Pujol Jover
**Editorial:** UOC · Primera edición digital: junio 2017
**Fuente:** Capítulo I, págs. 19-66

---

### Objetivos de aprendizaje
Al finalizar este notebook serás capaz de:
1. Instalar R, iniciar una sesión y gestionar paquetes (`install.packages`, `library`).
2. Consultar la ayuda oficial de R (`help()`).
3. Reconocer los tipos de datos y las clases de objetos de R (vector, matriz, lista, factor, fórmula...).
4. Crear, combinar e indexar vectores y matrices.
5. Escribir funciones propias, ciclos y condicionales.
6. Aplicar la familia `apply`/`tapply` para evitar bucles explícitos.
7. Construir y manipular `data.frame`, listas, fórmulas y factores.
8. Importar y exportar datos desde/hacia archivos de texto y CSV.
9. Identificar las extensiones gráficas de R (R-Commander, RStudio).

### Cómo usar este notebook
Cada apartado sigue el **mismo número de sección del libro** (p. ej. `2.3` = Matrices) e incluye:
- Una celda markdown con los conceptos clave y advertencias del texto.
- Una o varias celdas de código R con el fragmento correspondiente, comentado y con referencia de página.
Ejecuta las celdas en orden: varias reutilizan objetos (`a`, `datos`, `A`...) creados en celdas anteriores.

---
# 1. Primeros pasos con R

## 1.1. Instalación

### Conceptos clave
R se descarga gratuitamente desde el proyecto oficial **CRAN**: http://www.r-project.org/.
Tras acceder al centro de descargas, se elige el *mirror* más cercano y la versión
correspondiente al sistema operativo (Windows, Mac OS X o Linux).

No requiere código: es un proceso de instalación gráfico (pág. 19-20).

## 1.2. Iniciar una sesión

### Conceptos clave
Al ejecutar R se abre la **consola** (símbolo `>`). Las instrucciones se introducen tras ese símbolo
y se ejecutan pulsando *Enter*. En su uso más básico, R se comporta como una calculadora:
evalúa la expresión y muestra el resultado precedido por `[1]` (índice del primer elemento).
Para análisis largos conviene escribir las instrucciones en un **script** (archivo `.R`) y
ejecutarlas con `CONTROL + R`.

### Dependencias
Ninguna; estas operaciones pertenecen al paquete `base`, que se carga automáticamente.

In [ ]:
# ---------------------------------------------------------------
# 1.2 Iniciar una sesion: la consola como calculadora (pag. 21)
# ---------------------------------------------------------------

# Multiplicacion simple: R evalua la expresion y devuelve 6.
# La salida [1] 6 indica que el resultado es el primer (y unico) elemento.
2 * 3
# [1] 6

# ---------------------------------------------------------------
# Figura I.2 (pag. 21): asignar y mostrar con print()
# ---------------------------------------------------------------

# Asigna 7 al objeto 'a' (no se muestra nada al asignar)
a <- 2 + 5

# print() muestra explicitamente el contenido del objeto
print(a)
# [1] 7

## 1.3. Gestión de paquetes

### Conceptos clave
R es **modular**: sus funcionalidades se agrupan en *packages* (paquetes).
- `install.packages()` descarga e instala un paquete desde CRAN.
- `library()` lo carga en la sesión activa.
Una vez instalado, el paquete queda almacenado en disco; sólo es necesario cargarlo
(con `library`) al inicio de cada sesión en que se necesite.

### Advertencias
- Requiere conexión a Internet para la descarga.
- El nombre del paquete dentro de `install.packages` va entre comillas; dentro de `library`, no es obligatorio.

In [ ]:
# ---------------------------------------------------------------
# 1.3 Gestion de paquetes (pag. 22-24)
# ---------------------------------------------------------------

# Instalar un paquete desde CRAN.
# El argumento es el nombre del paquete entre comillas.
# Solo es necesario ejecutar esta linea una vez por maquina.
install.packages("paquete")

# Cargar el paquete en la sesion activa.
# Debe ejecutarse al principio de cada sesion en que se use el paquete.
library(paquete)

## 1.4. ¡Ayuda!

### Conceptos clave
R distingue **mayúsculas de minúsculas**, e incluye documentación oficial accesible
directamente desde la consola con `help()`, indicando el nombre del paquete o la función
entre paréntesis. Se abre una página con descripción, argumentos y ejemplos.

### Advertencias
> ⚠️ El lenguaje de R distingue mayúsculas/minúsculas: `HELP()` genera un error, mientras que `help()` funciona correctamente.

In [ ]:
# ---------------------------------------------------------------
# 1.4 Ayuda (pag. 24)
# ---------------------------------------------------------------

# Abre la pagina de ayuda de una funcion (aqui, mean)
help(mean)

# Forma abreviada equivalente a help()
?mean

# HELP(mean) fallaria: R distingue mayusculas de minusculas

---
# 2. Sintaxis y programación

## 2.1. Tipos de datos y objetos

### Conceptos clave
R es un lenguaje **orientado a objetos**. Los tres tipos básicos de datos son:
1. **Numéricos**: números reales y complejos (`-1, 2, 3`).
2. **Caracteres**: cadenas de texto entre comillas (`"x"`, `'y'`) — comillas simples y dobles son equivalentes.
3. **Lógicos**: únicamente `TRUE` o `FALSE`.

Sobre estos tipos se construyen ocho clases principales de objetos, que se detallan en el
resto del capítulo: `data frame`, `vector`, `array`, `matrix`, `list`, `function`, `factor` y `formula`.

No requiere código propio: es la base conceptual del resto de secciones (pág. 25-26).

## 2.2. Vectores

### 2.2.1. Almacenar datos en vectores

### Conceptos clave
El **vector** es la estructura de datos más simple en R.
- **Expresión:** R evalúa y muestra el resultado, pero NO lo guarda en memoria.
- **Asignación (`<-`):** R evalúa, guarda con el nombre dado y NO lo muestra (a menos que se encierre entre paréntesis).
- La función `c()` (*concatenar*) construye un vector a partir de valores individuales.
- Los espacios alrededor de `<-` son ignorados: `a <- 6` y `a<-6` son equivalentes.

In [ ]:
# ---------------------------------------------------------------
# 2.2.1a Expresion simple (pag. 26)
# El resultado se muestra pero NO se almacena.
# ---------------------------------------------------------------
4 + 3
# [1] 7

In [ ]:
# ---------------------------------------------------------------
# 2.2.1b Asignacion a un vector (pag. 27)
# ---------------------------------------------------------------

# Asigna un vector de 6 elementos al objeto 'a'.
# c() concatena los valores separados por comas.
# Tras la asignacion, R no muestra nada en pantalla.
a <- c(1, 2, 3, 4, 5, 6)

# Para ver el contenido, se escribe el nombre del objeto.
# Salida: [1] 1 2 3 4 5 6
a

In [ ]:
# ---------------------------------------------------------------
# 2.2.1c Asignacion con visualizacion inmediata (pag. 27)
# Encerrar la asignacion entre parentesis hace que el resultado
# se guarde Y se muestre simultaneamente.
# ---------------------------------------------------------------
(b <- c(3, 6, 9))
# [1] 3 6 9

In [ ]:
# ---------------------------------------------------------------
# 2.2.1d Combinacion de vectores (pag. 27)
# c() puede recibir como argumentos vectores ya creados.
# El resultado es la concatenacion de todos sus elementos.
# ---------------------------------------------------------------

# Vector 'a' con elementos 1, 2, 3
a <- c(1, 2, 3)

# Vector 'b' con elementos 7, 8, 9
b <- c(7, 8, 9)

# 'ab' combina: primero los elementos de 'a', luego 4,5,6, luego los de 'b'
ab <- c(a, 4, 5, 6, b)

# Muestra: [1] 1 2 3 4 5 6 7 8 9
ab

### 2.2.2. Operaciones aritméticas sobre vectores (Tabla I.1)

### Conceptos clave
Las operaciones en R están **vectorizadas**: se aplican elemento a elemento.
Esto significa que `v1 + v2` suma el primer elemento de `v1` con el primero de `v2`, etc.
Los decimales se expresan con **punto** (`.`), no con coma.

In [ ]:
# ---------------------------------------------------------------
# 2.2.2 Tabla I.1: Operaciones aritmeticas basicas (pag. 28)
# ---------------------------------------------------------------

# Definicion de vectores de ejemplo
v1 <- c(1, 2, 3)   # vector de 3 elementos
v2 <- c(2, 4, 6)   # vector de 3 elementos

# Concatenacion: une los dos vectores en uno solo
c(v1, v2)          # Resultado: 1,2,3,2,4,6

# Suma elemento a elemento
v1 + v2            # Resultado: 3,6,9

# Resta elemento a elemento
v1 - v2            # Resultado: -1,-2,-3

# Multiplicacion elemento a elemento
v1 * v2            # Resultado: 2,8,18

# Division elemento a elemento
v1 / v2            # Resultado: 0.5,0.5,0.5

# Potencia elemento a elemento (^ es el operador exponencial)
v1^v2              # Resultado: 1,16,729

### 2.2.3. Operaciones matemáticas elementales (Tabla I.2)

### Conceptos clave
Cuando una operación no está definida matemáticamente (p.ej., raíz de negativo),
R devuelve `NaN` (*Not a Number*).
Cuando el resultado tiende a infinito, devuelve `Inf` o `-Inf`.

In [ ]:
# ---------------------------------------------------------------
# 2.2.3 Tabla I.2: Operaciones matematicas elementales (pag. 29)
# v3 contiene un numero negativo para ilustrar NaN e Inf
# ---------------------------------------------------------------

# Vector de ejemplo con valores negativos, cero y positivos
v3 <- c(-1, 0, 1, 2)

# Raiz cuadrada: sqrt(-1) devuelve NaN porque no esta definida en los reales
sqrt(v3)      # NaN 0.00 1.00 1.41

# Valor absoluto
abs(v3)       # 1 0 1 2

# Funcion exponencial e^x
exp(v3)       # 0.36 1.00 2.71 7.38

# Logaritmo natural (base e): log(0) = -Inf, log(-1) = NaN
log(v3)       # NaN -Inf 0.00 0.69

# Logaritmo en base 10
log10(v3)     # NaN -Inf 0.00 0.30

# Factorial: el factorial de un numero negativo o no entero devuelve NaN
factorial(v3) # NaN 1 1 2

### 2.2.4. Operaciones estadísticas básicas (Tabla I.3)

### Conceptos clave
R incluye en el paquete `base` funciones estadísticas fundamentales que operan directamente
sobre vectores. La covarianza y correlación requieren **dos** vectores del mismo tamaño.

In [ ]:
# ---------------------------------------------------------------
# 2.2.4 Tabla I.3: Operaciones estadisticas basicas (pag. 29)
# ---------------------------------------------------------------

# Vectores de ejemplo
v4 <- c(-2, 3, 5, 0, 0, 3)
v5 <- c(20, 14, 51, 76, 21, 30)

# Numero de elementos del vector
length(v4)      # 6

# Valor maximo
max(v4)         # 5

# Valor minimo
min(v4)         # -2

# Suma de todos los elementos
sum(v4)         # 9

# Producto de todos los elementos (si hay un 0, el resultado es 0)
prod(v4)        # 0

# Media aritmetica
mean(v4)        # 1.5

# Mediana
median(v4)      # 1.5

# Desviacion estandar muestral (divide entre N-1)
sd(v4)          # 2.58

# Varianza muestral (sd^2)
var(v4)         # 6.7

# Covarianza muestral entre v4 y v5
cov(v4, v5)     # 5.8

# Correlacion de Pearson entre v4 y v5 (rango: -1 a 1)
cor(v4, v5)     # 0.09

# Producto escalar (suma del producto elemento a elemento)
sum(v4, v5)     # 347

### 2.2.5. Secuencias y repeticiones (Tabla I.4)

### Conceptos clave
Las funciones `seq()`, `rev()` y `rep()` son herramientas esenciales para crear
secuencias sin escribir cada valor manualmente.
- `seq(from, to, by)`: genera una secuencia regular.
- `rep(x, times)` / `rep(x, each)`: repite elementos.
- `rev(x)`: invierte el orden de un vector.
- El operador `:` es un atajo para `seq(from, to, by=1)`.

In [ ]:
# ---------------------------------------------------------------
# 2.2.5 Tabla I.4: Secuencias y repeticiones (pag. 30)
# ---------------------------------------------------------------

# Vector base de partida
v6 <- c(1, 2, 3)

# rep(v6, 2): repite el vector completo 2 veces
rep(v6, 2)                # 1 2 3 1 2 3

# rep(v6, each=2): repite cada elemento 2 veces antes de pasar al siguiente
rep(v6, each = 2)         # 1 1 2 2 3 3

# Combinacion: each=2 y times=2
rep(v6, each = 2, times = 2) # 1 1 2 2 3 3 1 1 2 2 3 3

# rep con vector de repeticiones por posicion
rep(v6, c(2, 3, 4))       # 1 1 2 2 2 3 3 3 3

# Secuencia del 1 al 10 con paso implicito de 1
1:10                      # 1 2 3 4 5 6 7 8 9 10

# Equivalente usando seq()
seq(1, 10)                # 1 2 3 4 5 6 7 8 9 10

# Secuencia decreciente del 10 al 1
10:1                      # 10 9 8 7 6 5 4 3 2 1

# Equivalente con seq()
seq(10, 1)                # 10 9 8 7 6 5 4 3 2 1

# seq con longitud especificada: 8 valores de 4 en adelante
seq(4, length = 8)        # 4 5 6 7 8 9 10 11

# seq con paso (by) de 5, entre 0 y 40
seq(0, 40, by = 5)        # 0 5 10 15 20 25 30 35 40

# seq con longitud 4 entre 0 y 1: crea 4 valores equidistantes
seq(0, 1, length = 4)     # 0.00 0.33 0.66 1.00

# seq especificando from, to y by
seq(from = 2, to = 8, by = 3) # 2 5 8

# rev(): invierte el vector 1:5
rev(1:5)                  # 5 4 3 2 1

# Operacion vectorizada aplicada a una secuencia: 2 * cada elemento de 1:4
2 * 1:4                   # 2 4 6 8

### 2.2.6. Secuencias con `expand.grid`

### Conceptos clave
`expand.grid()` genera un `data.frame` con **todas las combinaciones** de los vectores dados.
Es muy útil para crear secuencias temporales o de clasificación cruzada.

In [ ]:
# ---------------------------------------------------------------
# 2.2.6 expand.grid: secuencias encadenadas (pag. 31)
# Crea 8 observaciones: trimestres 1-4 para los anios 1996 y 1997.
# ---------------------------------------------------------------
expand.grid(trim = 1:4, anio = 1996:1997)

#   trim anio
# 1    1 1996
# 2    2 1996
# 3    3 1996
# 4    4 1996
# 5    1 1997
# 6    2 1997
# 7    3 1997
# 8    4 1997

### 2.2.7. Operadores lógicos (Tabla I.5)

### Conceptos clave
R opera con vectores lógicos (`TRUE`/`FALSE`).
- `&` es la intersección (AND elemento a elemento).
- `|` es la unión (OR elemento a elemento).
- `!` es la negación.
- El operador de **igualdad lógica** es `==` (doble igual), **distinto** de `=` (asignación).

In [ ]:
# ---------------------------------------------------------------
# 2.2.7 Tabla I.5: Operadores logicos (pag. 32)
# ---------------------------------------------------------------

# Vector con valores negativos, cero y positivos
a <- c(-2, -1, 0, 1, 2)

# Comprueba que elementos son estrictamente mayores que 2
a > 2
# [1] FALSE FALSE FALSE FALSE FALSE

# Comprueba que elementos son menores o iguales que -1
a <= -1
# [1] TRUE TRUE FALSE FALSE FALSE

# Interseccion (AND): elementos mayores que 0 Y con valor absoluto igual a 2
a > 0 & abs(a) == 2
# [1] FALSE FALSE FALSE FALSE TRUE

# Union (OR): elementos mayores que 0 O con valor absoluto igual a 2
a > 0 | abs(a) == 2
# [1] TRUE FALSE FALSE TRUE TRUE

### 2.2.8. Indexación de vectores (Tabla I.6)

### Conceptos clave
Los corchetes `[]` permiten **acceder, filtrar o modificar** elementos de un vector.
- Índice numérico positivo: selecciona las posiciones indicadas.
- Índice negativo: **excluye** esas posiciones.
- Condición lógica: selecciona los elementos que la satisfacen.
- La función `which()` devuelve los **índices** de los elementos que cumplen una condición.

In [ ]:
# ---------------------------------------------------------------
# 2.2.8a Tabla I.6: Indexacion de vectores (pag. 32-33)
# ---------------------------------------------------------------

# Definicion del vector v7
v7 <- c(-3, -2, -1, 0, 1, 2, 3)
# Forma compacta equivalente: v7 <- c(-3:3)

# Primer elemento
v7[1]                        # -3

# Elementos del segundo al cuarto
v7[2:4]                      # -2 -1 0

# Todos menos los elementos desde el segundo hasta el ultimo
v7[-(2:length(v7))]          # -3

# Elementos en las posiciones 2, 4 y 6
v7[c(2, 4, 6)]               # -2  0  2

# Elementos estrictamente mayores que 0
v7[v7 > 0]                   # 1 2 3

# Elementos distintos de 0
v7[v7 != 0]                  # -3 -2 -1 1 2 3

# Elementos cuyo valor absoluto es exactamente 3
v7[abs(v7) == 3]             # -3 3

# Elementos positivos Y que no sean 2
v7[v7 > 0 & v7 != 2]        # 1 3

# Elementos negativos O iguales a 3
v7[v7 < 0 | v7 == 3]        # -3 -2 -1 3

In [ ]:
# ---------------------------------------------------------------
# 2.2.8b Funcion which(): posiciones ordinales (pag. 33-34)
# which() devuelve los INDICES (posiciones) de los TRUE,
# no los valores en si.
# ---------------------------------------------------------------

# Vector con ceros y valores distintos de cero
a <- c(0, 3, 0, 1, 3, 0)

# Posiciones donde a == 0: primera (indice 1), tercera (3) y sexta (6)
which(a == 0)
# [1] 1 3 6

# Posicion del unico elemento que es > 0 y <= 2: cuarta posicion (valor 1)
which(a > 0 & a <= 2)
# [1] 4

# which.min() y which.max() devuelven la posicion del minimo y maximo

## 2.3. Matrices

### Conceptos clave
Una **matriz** es un caso particular de `array` con exactamente 2 dimensiones (filas × columnas).
- `dim(v) <- c(nrow, ncol)`: convierte un vector en matriz asignándole dimensiones.
- `matrix(data, nrow, ncol)`: función directa para crear matrices.
- Por defecto, R llena las matrices **por columnas** (de arriba abajo, izquierda a derecha).
- `byrow=TRUE`: invierte el orden de llenado a por filas.
- **Reciclaje:** si los datos son insuficientes, R repite el vector inicial hasta completar la estructura.

### Advertencia
> ⚠️ Cuando una submatriz tiene una sola fila o columna, R la "degrada" a vector (pierde la dimensión). Use `drop=FALSE` para evitarlo.

In [ ]:
# ---------------------------------------------------------------
# 2.3a Asignar dimension a un vector (pag. 34)
# ---------------------------------------------------------------

# Vector de 8 elementos
a <- 1:8
a
# [1] 1 2 3 4 5 6 7 8

# Longitud del vector
length(a)
# [1] 8

# Un vector no tiene dimension: devuelve NULL
dim(a)
# NULL

# Convertir en matriz 4x2 asignando dimension
# (se llena por columnas: columna 1 = 1,2,3,4; columna 2 = 5,6,7,8)
dim(a) <- c(4, 2)
a
#      [,1] [,2]
# [1,]    1    5
# [2,]    2    6
# [3,]    3    7
# [4,]    4    8

# Confirmar dimensiones: 4 filas, 2 columnas
dim(a)
# [1] 4 2

In [ ]:
# ---------------------------------------------------------------
# 2.3b Funcion matrix() (pag. 35)
# Argumentos: (datos, numero_de_filas, numero_de_columnas)
# ---------------------------------------------------------------

# Matriz 2x4 con los valores 1:8 (por columnas, por defecto)
matrix(1:8, 2, 4)
#      [,1] [,2] [,3] [,4]
# [1,]    1    3    5    7
# [2,]    2    4    6    8

In [ ]:
# ---------------------------------------------------------------
# 2.3c array() para mas de 2 dimensiones (pag. 36)
# Estructura 2x2x2: el vector 1:4 se recicla para completar los 8 elementos.
# ---------------------------------------------------------------
array(1:4, c(2, 2, 2))

# , , 1          (primera "capa")
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

# , , 2          (segunda "capa", reciclaje del vector)
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

In [ ]:
# ---------------------------------------------------------------
# 2.3d Reciclaje ilustrado (pag. 37)
# matrix(1:3, 3, 3): el vector 1,2,3 se repite hasta llenar 9 celdas.
# ---------------------------------------------------------------
matrix(1:3, 3, 3)
#      [,1] [,2] [,3]
# [1,]    1    1    1
# [2,]    2    2    2
# [3,]    3    3    3

In [ ]:
# ---------------------------------------------------------------
# 2.3e Llenado por filas con byrow=TRUE (pag. 37)
# matrix(1:8, 2, 4, byrow=TRUE): fila 1 = 1,2,3,4; fila 2 = 5,6,7,8
# ---------------------------------------------------------------
matrix(1:8, 2, 4, byrow = TRUE)
#      [,1] [,2] [,3] [,4]
# [1,]    1    2    3    4
# [2,]    5    6    7    8

In [ ]:
# ---------------------------------------------------------------
# 2.3f Especificar solo nrow o ncol (pag. 38)
# R infiere la dimension faltante a partir del tamanio de los datos.
# ---------------------------------------------------------------

# Solo numero de filas: R calcula ncol = 6/2 = 3
matrix(1:6, nrow = 2)
#      [,1] [,2] [,3]
# [1,]    1    3    5
# [2,]    2    4    6

# Solo numero de columnas: R calcula nrow = 4/2 = 2
matrix(1:4, ncol = 2)
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

In [ ]:
# ---------------------------------------------------------------
# 2.3g rbind() y cbind(): combinar matrices (pag. 38)
# rbind(): une por FILAS (mismas columnas). cbind(): une por COLUMNAS (mismas filas).
# ---------------------------------------------------------------

# Matriz de ceros 2x2
a <- matrix(0, 2, 2)
a
#      [,1] [,2]
# [1,]    0    0
# [2,]    0    0

# Matriz de unos 1x2
b <- matrix(1, 1, 2)
b
#      [,1] [,2]
# [1,]    1    1

# Unir 'a' y 'b' por filas: resultado 3x2
rbind(a, b)
#      [,1] [,2]
# [1,]    0    0
# [2,]    0    0
# [3,]    1    1

In [ ]:
# ---------------------------------------------------------------
# 2.3h cbind() con escalar y vector (pag. 39)
# Al unir un escalar y un vector, el escalar se repite
# tantas veces como elementos tenga el vector.
# ---------------------------------------------------------------
cbind(1, 1:4)
#      [,1] [,2]
# [1,]    1    1
# [2,]    1    2
# [3,]    1    3
# [4,]    1    4

In [ ]:
# ---------------------------------------------------------------
# 2.3i Matriz identidad con diag() (pag. 39)
# diag(n) crea una matriz identidad de tamanio n x n.
# Sobre una matriz existente, diag() extrae la diagonal principal.
# ---------------------------------------------------------------

# Matriz identidad 2x2
diag(2)
#      [,1] [,2]
# [1,]    1    0
# [2,]    0    1

# Extraer la diagonal principal de una matriz 2x2
a <- matrix(5 * 1:4, 2, 2)
a
#      [,1] [,2]
# [1,]    5   15
# [2,]   10   20

# Los elementos diagonales son 5 (posicion [1,1]) y 20 (posicion [2,2])
diag(a)
# [1]  5 20

### Submatrices e indexación (Tabla I.7)

### Conceptos clave
La indexación de matrices usa dos índices dentro de `[]`: `[fila, columna]`.
- Dejar un índice en blanco selecciona **todas** las filas o columnas.
- El índice negativo **excluye** filas o columnas.
- Se pueden usar los corchetes en el lado izquierdo de `<-` para **modificar** partes de la matriz.

In [ ]:
# ---------------------------------------------------------------
# 2.3j Tabla I.7: Indexacion de matrices (pag. 39-40)
# ---------------------------------------------------------------

# Matriz 3x3 de partida (multiplos de 3, llenado por columnas)
a <- matrix(1:9 * 3, 3, 3)
a
#      [,1] [,2] [,3]
# [1,]    3   12   21
# [2,]    6   15   24
# [3,]    9   18   27

# Todas las filas, columna 3
a[, 3]         # 21 24 27

# Fila 2, todas las columnas
a[2, ]         # 6 15 24

# Todas las filas menos la primera, todas las columnas menos la tercera
a[-1, -3]
#      [,1] [,2]
# [1,]    6   15
# [2,]    9   18

# De la fila 2 a la 3, columna 1
a[2:3, 1]      # 6 9

In [ ]:
# ---------------------------------------------------------------
# 2.3k drop=FALSE para preservar la dimension (pag. 41)
# Sin drop=FALSE, una submatriz de una columna se degrada a vector.
# ---------------------------------------------------------------

# Matriz pequenia de partida
a <- matrix(1:6, 2, 3)
a
#      [,1] [,2] [,3]
# [1,]    1    3    5
# [2,]    2    4    6

# Extraer la columna 1 conservando la estructura de matriz (no vector)
b <- a[, 1, drop = FALSE]
b
#      [,1]
# [1,]    1
# [2,]    2

# Confirmar que b sigue siendo una matriz (tiene dimension)
dim(b)
# [1] 2 1

In [ ]:
# ---------------------------------------------------------------
# 2.3l Modificar elementos de una matriz (pag. 41)
# El lado izquierdo de <- con indexacion reemplaza los valores seleccionados.
# ---------------------------------------------------------------

# Crear matriz 2x4
a <- matrix(1:8, 2, 4)

# Reemplazar toda la primera columna con ceros
a[, 1] <- 0

a
#      [,1] [,2] [,3] [,4]
# [1,]    0    3    5    7
# [2,]    0    4    6    8

### Operaciones matriciales básicas (Tabla I.8) y funciones `is.` / `as.`

### Conceptos clave
- La familia `is.*()` responde con `TRUE`/`FALSE` si el objeto es de la clase indicada.
- La función `class()` devuelve el tipo del objeto.
- La familia `as.*()` **transforma** un objeto de un tipo a otro.

In [ ]:
# ---------------------------------------------------------------
# 2.3m is., class() y as. (pag. 41-42)
# ---------------------------------------------------------------

# Vector numerico de ejemplo
a <- c(1, 3, 6)

# Es una matriz? -> FALSE (es un vector)
is.matrix(a)
# [1] FALSE

# Es un vector? -> TRUE
is.vector(a)
# [1] TRUE

# Clase del objeto
class(a)
# [1] "numeric"

# Convertir la matriz A en vector con as.vector()
# (los elementos se extraen por columnas)
(A <- matrix(1, 2, 2))
#      [,1] [,2]
# [1,]    1    1
# [2,]    1    1

(a <- as.vector(A))
# [1] 1 1 1 1

## 2.4. Funciones

### Conceptos clave
El comando `function()` crea un objeto de tipo función.
La sintaxis general es:
```
nombre <- function(argumentos) expresión
```
Para funciones de más de una línea se usa `{}` y se termina con `return(resultado)`.

In [ ]:
# ---------------------------------------------------------------
# 2.4a Funcion de una linea: y = x^3 (pag. 42)
# ---------------------------------------------------------------

# Definir la funcion cubic: recibe 'x', devuelve x elevado al cubo
cubic <- function(x) x^3

# Vector de valores de evaluacion: -4, -3, ..., 3, 4
x0 <- (-4:4)

# Evaluar la funcion en el vector x0 (operacion vectorizada automaticamente)
cubic(x0)
# [1] -64 -27  -8  -1   0   1   8  27  64

In [ ]:
# ---------------------------------------------------------------
# 2.4b Funcion con multiples argumentos: interes simple (pag. 43)
# Formula: Cf = Ci * (1 + r*t)
#   Ci: capital inicial
#   r:  tipo de interes (en tanto por uno)
#   t:  tiempo en anios
# ---------------------------------------------------------------

# Definicion de la funcion
op.fin <- function(Ci, r, t) Ci * (1 + r * t)

# Ejemplo: capital inicial 1000, tasa 5% (0.05), 9 meses (0.75 anios)
op.fin(1000, 0.05, 0.75)
# [1] 1037.5

In [ ]:
# ---------------------------------------------------------------
# 2.4c Funcion de multiples lineas: covarianza muestral (pag. 44)
# Formula: Cov(X,Y) = (1/(N-1)) * sum((xi - x_bar)(yi - y_bar))
# Parametros de entrada:
#   x: vector numerico (primera variable)
#   y: vector numerico (segunda variable, misma longitud que x)
# Valor de retorno: escalar numerico (covarianza muestral)
# Nota: equivalente a cov(x,y) del paquete base; se implementa
#       manualmente con fines didacticos.
# ---------------------------------------------------------------

mi.covar <- function(x, y) {
  N        <- length(x)          # Numero de observaciones
  demean.x <- x - mean(x)        # Desvios de x respecto a su media
  demean.y <- y - mean(y)        # Desvios de y respecto a su media
  sumat    <- sum(demean.x * demean.y) # Suma del producto de desvios
  return(sumat / (N - 1))        # Divide entre N-1 (covarianza muestral)
}

## 2.5. Ciclos y condicionales

### Conceptos clave
- `ifelse(condicion, valor_si_TRUE, valor_si_FALSE)`: condicional **vectorizado** (opera sobre todos los elementos a la vez).
- `for (i in secuencia) { ... }`: bucle iterativo clásico.
  En R se desaconseja su uso cuando existen alternativas vectorizadas, ya que es menos eficiente.

### Advertencia
> ⚠️ En análisis real, `cumsum()` es más eficiente que un bucle para calcular sumas acumulativas.

In [ ]:
# ---------------------------------------------------------------
# 2.5a ifelse(): condicional vectorizado (pag. 45)
# Aplica la transformacion:
#   f(x) = log(x)  si x > 0
#   f(x) = 0       si x <= 0
# ---------------------------------------------------------------

# Vector con valores negativos, cero y positivos
a <- c(-1, 0, 2, 5)

# ifelse evalua la condicion elemento a elemento:
#   Para a > 0: aplica log(a)
#   Para el resto: devuelve 0
ifelse(a > 0, log(a), 0)
# [1] 0.0000000 0.0000000 0.6931472 1.6094379

In [ ]:
# ---------------------------------------------------------------
# 2.5b Ciclo for: suma acumulativa (pag. 46)
# Calcula el vector s donde s[j] = suma de v[1..j]
# ---------------------------------------------------------------

# Vector de 1 a 10
v <- 1:10

# Numero de elementos
n <- length(v)

# Inicializar vector resultado con n ceros
s <- rep(0, n)

# Bucle: en cada iteracion i, suma los primeros i elementos de v
for (i in 1:n) {
  p    <- v[1:i]      # Subvector v[1..i]
  s[i] <- sum(p)      # Suma acumulada hasta la posicion i
}

# Mostrar resultado
print(s)
# [1]  1  3  6 10 15 21 28 36 45 55

## 2.6. La familia `apply`

### Conceptos clave
- `apply(matriz, margen, funcion)`: aplica una función a las filas (`margen=1`) o columnas (`margen=2`) de una matriz.
- `tapply(variable, factor, funcion)`: aplica una función a subgrupos definidos por las categorías de un factor.
- Son más eficientes que los ciclos `for` para operaciones sobre estructuras.

### Dependencias
Paquete `base` (sin instalación adicional).

In [ ]:
# ---------------------------------------------------------------
# 2.6a apply() sobre filas de una matriz (pag. 46-47)
# Aplica la funcion hipot (norma euclidea de un vector) a cada fila de A.
# La instruccion apply(A,1,hipot) se lee:
# "aplica a la dimension 1 (filas) de A la operacion hipot"
# ---------------------------------------------------------------

# Funcion que calcula la norma euclidea de un vector x: sqrt(sum(x^2))
hipot <- function(x) sqrt(sum(x * x))

# A es una matriz donde filas = observaciones, columnas = variables X, Y, Z
A <- matrix(c(3, 4, 6, 8, 0, 5, 12, 9, 4), nrow = 3)

# apply(A, 1, hipot) aplica 'hipot' a cada FILA (resultado: vector de 3 elementos)
apply(A, 1, hipot)

In [ ]:
# ---------------------------------------------------------------
# 2.6b apply() sobre columnas (pag. 47)
# Calcula la media aritmetica de cada columna de A.
# El resultado es el vector (x_bar, y_bar, z_bar).
# ---------------------------------------------------------------

# apply(A, 2, mean) aplica 'mean' a cada COLUMNA (resultado: vector de 3 elementos)
apply(A, 2, mean)

### `factor()` sobre un vector de caracteres (pág. 47-48)

Antes de aplicar `tapply()` por grupos es necesario convertir la variable de agrupación
(en este caso, el texto `"m"`/`"f"`) en un **factor**. `levels()` devuelve las categorías
presentes, en orden alfanumérico.

In [ ]:
# ---------------------------------------------------------------
# 2.6c factor() sobre vector de caracteres + cbind (pag. 47-48)
# Paso previo a tapply(): construir el factor de agrupacion.
# ---------------------------------------------------------------

# Vectores de datos de estudiantes
altura <- c(131, 125, 126, 140, 152, 119)
genero <- c('m', 'm', 'f', 'm', 'f', 'f')

# Convertir el vector de caracteres en factor
f.genero <- factor(genero)

# Verificar que los tipos son distintos
class(genero)    # "character"
class(f.genero)  # "factor"

# Categorias del factor (orden alfanumerico: f antes que m)
levels(f.genero)
# [1] "f" "m"

# Combinar el factor y la variable numerica en una matriz
# (el factor se convierte internamente a su codigo numerico: f=1, m=2)
cbind(f.genero, altura)
#      f.genero altura
# [1,]        2    131
# [2,]        2    125
# [3,]        1    126
# [4,]        2    140
# [5,]        1    152
# [6,]        1    119

### `tapply()`: estadísticas por grupos (pág. 48-49)

In [ ]:
# ---------------------------------------------------------------
# 2.6d tapply(): estadisticas por grupos (pag. 48-49)
# Calcula media y desviacion estandar de 'altura' diferenciando por genero.
# Reutiliza 'altura' y 'f.genero' definidos en la celda anterior.
# ---------------------------------------------------------------

# Media de altura por genero: argumentos = (variable, factor, funcion)
tapply(altura, f.genero, mean)
#        f        m
# 132.3333 132.0000

# Desviacion estandar de altura por genero
tapply(altura, f.genero, sd)
#         f         m
# 17.387735  7.549834

## 2.7. Bases de datos (`data.frame`)

### Conceptos clave
Un `data.frame` es una estructura bidimensional donde cada columna puede tener un tipo diferente
(numérica, carácter, factor…).
- `data.frame()`: crea el objeto.
- `$`: accede a una variable por nombre.
- `subset()`: filtra observaciones con condiciones.
- `attach()`: "vuelca" las variables al espacio de trabajo para referenciarlas directamente.

In [ ]:
# ---------------------------------------------------------------
# 2.7a Crear un data.frame desde vectores (pag. 49-50)
# ---------------------------------------------------------------

# Vector de genero (caracter)
g  <- c('m', 'm', 'f', 'm', 'f', 'f')   # Genero

# Vector de alturas (numerico)
v1 <- c(131, 125, 126, 140, 152, 119)   # Altura

# Vector de pesos (numerico)
v2 <- c(48, 53, 45, 40, 49, 50)         # Peso

# Crear data.frame asignando nombres a las columnas
datos <- data.frame(genero = g, altura = v1, peso = v2)

# Mostrar el data.frame
datos
#   genero altura peso
# 1      m    131   48
# 2      m    125   53
# 3      f    126   45
# 4      m    140   40
# 5      f    152   49
# 6      f    119   50

In [ ]:
# ---------------------------------------------------------------
# 2.7b subset(): crear subconjuntos (pag. 51)
# Filtra hombres (genero=="m") con peso menor a 50 kg.
# ---------------------------------------------------------------
datos2 <- subset(datos, genero == "m" & peso < 50)
datos2
#   genero altura peso
# 1      m    131   48
# 4      m    140   40

In [ ]:
# ---------------------------------------------------------------
# 2.7c Acceso con $ y funcion attach() (pag. 51-52)
# ---------------------------------------------------------------

# Para operar con variables individuales se usa el operador $
# Correlacion entre altura y peso usando $ para referenciar columnas
cor(datos$altura, datos$peso)
# [1] -0.3202351

# attach() vuelca las variables del data.frame al espacio de trabajo,
# permitiendo referenciarlas directamente (sin el prefijo datos$)
attach(datos)

# Ahora se puede llamar directamente a 'altura' y 'peso' sin el prefijo
cor(altura, peso)
# [1] -0.3202351

## 2.8. Listas

### Conceptos clave
Una **lista** puede almacenar objetos de **clases distintas** en una única estructura.
- `list(nombre=objeto, ...)`: crea la lista.
- `lista$nombre`: accede al elemento por nombre.
- `lista[[n]]`: accede al n-ésimo elemento por posición.

In [ ]:
# ---------------------------------------------------------------
# 2.8 Listas: crear y acceder a elementos (pag. 51-54)
# ---------------------------------------------------------------

# Definicion de componentes de distinto tipo
descr <- c('Matriz A')               # Vector de caracteres
A     <- matrix(c(3, 5, 6, 1), 2, 2) # Matriz 2x2
inv   <- solve(A)                    # Inversa de A (funcion del paquete base)
deter <- det(A)                      # Determinante de A

# Crear lista con 4 elementos de clases distintas
MatA <- list(descripcion = descr,
             matriz      = A,
             inversa     = inv,
             deter       = deter)

# Acceder al elemento 'descripcion' por nombre con $
MatA$descripcion
# [1] "Matriz A"

# Acceder al elemento 'matriz' por nombre
MatA$matriz
#      [,1] [,2]
# [1,]    3    6
# [2,]    5    1

# Acceder a la inversa por nombre
MatA$inversa
#              [,1]      [,2]
# [1,] -0.03703704  0.2222222
# [2,]  0.18518519 -0.1111111

# Acceder al determinante por nombre
MatA$deter
# [1] -27

# Acceder al cuarto elemento por posicion ordinal con [[ ]]
MatA[[4]]
# [1] -27
# Nota: MatA[[2]] y MatA$matriz dan el mismo resultado.

## 2.9. Fórmulas

### Conceptos clave
Una **fórmula** en R especifica la relación entre variables usando el operador `~`:
variable dependiente `~` variable(s) explicativa(s).
Se almacena como objeto para reutilizarla en distintos modelos.

In [ ]:
# ---------------------------------------------------------------
# 2.9 Formulas y modelos de regresion (pag. 54-55)
# ---------------------------------------------------------------

# Estimar directamente un modelo de regresion:
# y es la variable dependiente; x1, x2, x3 son los regresores.
# lm() ajusta por minimos cuadrados ordinarios (MCO).
modelo.1 <- lm(y ~ x1 + x2 + x3)

# Almacenar la especificacion como objeto de tipo 'formula'
# para reutilizarla en varias instrucciones
ecuacion.1 <- formula(y ~ x1 + x2 + x3)

# Usar el objeto formula en lugar de escribirla de nuevo
modelo.1 <- lm(ecuacion.1)

## 2.10. Factores

### Conceptos clave
Los **factores** son vectores que representan variables **cualitativas** (categorías).
- `factor(vector, labels=c(...))`: convierte un vector numérico en factor con etiquetas.
- `levels()`: muestra las categorías disponibles.
- `class()`: devuelve `"factor"` en lugar de `"character"` o `"numeric"`.
- `unstack()` / `stack()`: reorganizan datos entre formato ancho y largo.

In [ ]:
# ---------------------------------------------------------------
# 2.10a Crear un factor con etiquetas (pag. 55-56)
# ---------------------------------------------------------------

# Variables numericas de ejemplo
x <- c(3, 2, 4, 5, 6, 4)   # Atributo cuantitativo
y <- c(0, 0, 1, 1, 0, 1)   # Indicador de genero: 0=Hombre, 1=Mujer

# Mostrar combinacion de variables
cbind(x, y)
#      x y
# [1,] 3 0
# [2,] 2 0
# [3,] 4 1
# [4,] 5 1
# [5,] 6 0
# [6,] 4 1

# Convertir y en factor asignando etiquetas:
# valor 0 -> "Hombre", valor 1 -> "Mujer" (orden creciente)
genero <- factor(y, labels = c("Hombre", "Mujer"))

# Verificar que 'y' sigue siendo numerico y 'genero' es factor
class(y)
# [1] "numeric"
class(genero)
# [1] "factor"

In [ ]:
# ---------------------------------------------------------------
# 2.10b data.frame con factor y stack/unstack (pag. 56-57)
# ---------------------------------------------------------------

# Crear data.frame combinando la variable cuantitativa y el factor
datos.1 <- data.frame(x, genero)
print(datos.1)
#   x genero
# 1 3 Hombre
# 2 2 Hombre
# 3 4  Mujer
# 4 5  Mujer
# 5 6 Hombre
# 6 4  Mujer

# unstack(): transforma de formato largo a ancho.
# Crea una variable por cada categoria del factor.
datos.2 <- unstack(datos.1)
print(datos.2)
#   Hombre Mujer
# 1      3     4
# 2      2     5
# 3      6     4

# stack(): operacion inversa a unstack().
# Apila las columnas en una sola variable y crea la columna 'ind' (indicador/factor).
datos.3 <- stack(datos.2)
print(datos.3)
#   values    ind
# 1      3 Hombre
# 2      2 Hombre
# 3      6 Hombre
# 4      4  Mujer
# 5      5  Mujer
# 6      4  Mujer

---
# 3. Importación y exportación de datos

### Conceptos clave
Antes de importar datos es necesario definir el **directorio de trabajo** con `setwd()`.
- `read.table()`: función general para importar datos desde texto plano.
- `read.csv()` / `read.csv2()`: atajos optimizados para archivos CSV.
- `write.table()` / `write.csv()`: exportan objetos a archivos de texto.

### Advertencias
> ⚠️ Las rutas en Windows usan `/` o `\\` (doble barra inversa), nunca `\` simple.

In [ ]:
# ---------------------------------------------------------------
# 3a Definir directorio de trabajo (pag. 57)
# Todos los archivos importados/exportados se buscan en este directorio.
# ---------------------------------------------------------------
setwd("C:/directorio")

In [ ]:
# ---------------------------------------------------------------
# 3b read.table(): importacion de datos (pag. 57-58)
# Importa el archivo "Datos.txt" y lo convierte en un data.frame.
# Argumentos:
#   header    : TRUE = primera fila contiene nombres de variables
#   sep       : separador entre valores (" " = espacio en blanco)
#   dec       : caracter decimal ("." = punto)
#   row.names : nombres de las filas
#   col.names : nombres de las columnas
# ---------------------------------------------------------------
base.datos <- read.table("Datos.txt",
  header = TRUE, sep = "", dec = ".",
  row.names = NULL, col.names = NULL)

In [ ]:
# ---------------------------------------------------------------
# 3c write.table(): exportacion de datos (pag. 59-60)
# Exporta el objeto 'x' al archivo "resultado.txt".
# Argumentos:
#   sep        : separador entre valores (" " = espacio)
#   na         : caracter para valores ausentes ("NA")
#   dec        : separador decimal (".")
#   row.names  : TRUE = incluir nombres de filas
#   col.names  : TRUE = incluir nombres de columnas
# ---------------------------------------------------------------
write.table(x, file = "resultado.txt",
  sep = " ", na = "NA", dec = ".",
  row.names = TRUE, col.names = TRUE)

In [ ]:
# ---------------------------------------------------------------
# 3d write.csv(): exportar a formato CSV (pag. 60)
# Genera un archivo legible por Excel y OpenOffice.
# Las opciones son las mismas que write.table().
# ---------------------------------------------------------------
write.csv(x, file = "resultado.csv")

---
# 4. Extensiones de R

### Conceptos clave
La flexibilidad de R ha dado lugar a extensiones gráficas que facilitan su uso:
- **R-Commander** (`Rcmdr`): interfaz de menús desplegables creada por John Fox; muestra
  en pantalla el código R subyacente a cada acción, lo que la hace ideal para aprender.
  Se relanza sin cerrar R con `Commander()`.
- **RStudio**: entorno de desarrollo integrado (IDE) para usuarios avanzados, con paneles
  para script, consola, objetos del entorno y gráficos.
- **Deducer**: alternativa basada en Java, similar a R-Commander, con más énfasis gráfico.

In [ ]:
# ---------------------------------------------------------------
# 4.1 R-Commander: instalacion y arranque (pag. 60-61)
# ---------------------------------------------------------------

# Instalar el paquete Rcmdr (una sola vez)
install.packages("Rcmdr")

# Cargar R-Commander (necesario en cada sesion en que se use)
library(Rcmdr)

# Si se cierra la ventana de R-Commander sin cerrar R,
# se puede volver a abrir sin recargar el paquete:
Commander()

## 4.2. RStudio (pág. 65)

Ejemplo mostrado en la Figura I.4: genera 10.000 observaciones de una normal y dibuja su histograma.

In [ ]:
# ---------------------------------------------------------------
# 4.2 Ejemplo de la Figura I.4 en RStudio (pag. 65)
# rnorm(n, media, sd) genera valores aleatorios de una distribucion normal.
# ---------------------------------------------------------------
a <- rnorm(10000, 10, 5)
hist(a, col = "grey")

---
## Conclusión

### Qué cubre este notebook
Este notebook documenta de forma exhaustiva el **Capítulo I** del libro
*Análisis cuantitativo con R* (Liviano & Pujol, 2017), siguiendo el mismo orden
y numeración de secciones que el texto original.

| Sección del libro | Tema | Funciones clave |
|---|---|---|
| 1.1-1.2 | Instalación e inicio de sesión | consola, `print()` |
| 1.3 | Gestión de paquetes | `install.packages()`, `library()` |
| 1.4 | Ayuda | `help()`, `?` |
| 2.1 | Tipos de datos y objetos | — (conceptual) |
| 2.2 | Vectores y operaciones | `c()`, `<-`, `:`, `seq()`, `rep()`, `rev()`, `which()` |
| 2.3 | Matrices | `matrix()`, `array()`, `rbind()`, `cbind()`, `diag()`, `is.*()`, `as.*()` |
| 2.4 | Funciones propias | `function()`, `return()` |
| 2.5 | Control de flujo | `ifelse()`, `for` |
| 2.6 | Familia apply | `apply()`, `tapply()` |
| 2.7 | Bases de datos | `data.frame()`, `subset()`, `attach()` |
| 2.8 | Listas | `list()`, `$`, `[[]]` |
| 2.9 | Fórmulas | `formula()`, `lm()` |
| 2.10 | Factores | `factor()`, `levels()`, `stack()`, `unstack()` |
| 3 | Importación/exportación | `setwd()`, `read.table()`, `write.table()`, `write.csv()` |
| 4 | Extensiones de R | `Rcmdr`, `Commander()`, RStudio |

### Cómo ejecutar
1. Abrir en **Jupyter Lab**, **VS Code** o **Google Colab** con kernel `R`.
2. Ejecutar las celdas en orden: varias reutilizan objetos (`a`, `datos`, `A`, `f.genero`...) creados en celdas anteriores.
3. Las celdas de importación/exportación (Sección 3) y R-Commander (Sección 4.1) requieren
   rutas/paquetes reales para ejecutarse sin error; se documentan tal como aparecen en el libro.

---
*Notebook estandarizado a partir del PDF oficial del capítulo (Cap01_Estructura_Lenguaje_Sintaxis_R.pdf).*
*Referencia: Liviano Solís, D. & Pujol Jover, M. (2017). Análisis cuantitativo con R: matemáticas, estadística y econometría. Editorial UOC.*