# Capítulo II – Álgebra Lineal y Cálculo con R
## Análisis Cuantitativo con R: Matemáticas, Estadística y Econometría

**Autores del libro:** Daniel Liviano Solís · Maria Pujol Jover
**Editorial:** UOC · Primera edición digital: junio 2017
**Fuente:** Capítulo II, págs. 67-122

---

### Objetivos de aprendizaje
Al finalizar este notebook serás capaz de:
1. Operar vectores y matrices (suma, producto elemento a elemento, producto matricial, Kronecker).
2. Resolver ecuaciones algebraicas y sistemas de ecuaciones lineales.
3. Calcular la descomposición espectral (`eigen`) y en valores singulares (`svd`) de una matriz.
4. Definir, evaluar y graficar funciones matemáticas en una y varias dimensiones.
5. Calcular derivadas simbólicas/numéricas e integrales numéricas.
6. Resolver ecuaciones diferenciales ordinarias con el paquete `deSolve`.
7. Optimizar funciones de una y varias variables (`optimize`, `optim`).
8. Operar con números complejos y calcular raíces complejas n-ésimas.

### Cómo usar este notebook
Cada apartado sigue el **mismo número de sección del libro** (p. ej. `4.2` = Integración).
Ejecuta las celdas en orden: varias reutilizan objetos (`A`, `B`, `f.v`, `t.0`...) creados en celdas anteriores.

---
# 2. Álgebra vectorial y matricial
## 2.1. Operaciones algebraicas (pág. 68-79)

### 2.1.1. Suma de escalares con vectores

R opera de forma **vectorizada**: al sumar un escalar a un vector, el valor se aplica a cada elemento individualmente.

In [ ]:
# ---------------------------------------------------------------
# 2.1.1 Suma de escalares con vectores (pag. 68)
# ---------------------------------------------------------------

# Crear un vector con los enteros del 1 al 4
v <- 1:4

# Sumar el escalar 5 a cada elemento del vector v
# Resultado esperado: 6 7 8 9
5 + v
# [1] 6 7 8 9

### 2.1.2. Suma y resta entre vectores

Para sumar o restar dos vectores elemento a elemento, ambos deben tener la **misma longitud**.

In [ ]:
# ---------------------------------------------------------------
# 2.1.2 Suma y resta entre vectores (pag. 68-69)
# ---------------------------------------------------------------

# Crear vector a con valores 1, 2, 3, 4, 5
a <- 1:5

# Crear vector b con valores 5, 4, 3, 2, 1 (secuencia inversa)
b <- 5:1

# Suma elemento a elemento: cada par suma 6
a + b
# [1] 6 6 6 6 6

# Resta elemento a elemento
a - b
# [1] -4 -2  0  2  4

### 2.1.3. Suma de escalares con matrices

`matrix(data, nrow, ncol)` construye una matriz rellenando **por columnas** por defecto.

In [ ]:
# ---------------------------------------------------------------
# 2.1.3 Suma de escalares con matrices (pag. 69)
# ---------------------------------------------------------------

# Crear matriz A de dimension 2x2 con valores del 1 al 4
# Llenado por columna: col1 = {1,2}, col2 = {3,4}
A <- matrix(1:4, 2, 2)

# Sumar el escalar 3 a todos los elementos de A
3 + A
#      [,1] [,2]
# [1,]    4    6
# [2,]    5    7

### 2.1.4. Suma entre matrices de igual dimensión

La suma matricial se realiza **elemento por elemento** y requiere que ambas matrices tengan exactamente las mismas dimensiones.

In [ ]:
# ---------------------------------------------------------------
# 2.1.4 Suma entre matrices de igual dimension (pag. 69-70)
# ---------------------------------------------------------------

# Crear matriz A (2x2) con valores 1 a 4
A <- matrix(1:4, 2, 2)

# Crear matriz B (2x2) con valores desde 4
B <- matrix(4, 2, 2)

# Suma elemento a elemento de A y B
A + B
#      [,1] [,2]
# [1,]    5    7
# [2,]    6    8

### 2.1.5. Reciclaje de vectores en operaciones con matrices (pág. 70-71)

Cuando la longitud de un vector es **múltiplo** del número total de elementos de la matriz, R rellena la operación reciclando los valores del vector. Si no es múltiplo exacto, genera una advertencia.

> ⚠️ R opera por columnas (de arriba abajo, de izquierda a derecha) al reciclar.

In [ ]:
# ---------------------------------------------------------------
# 2.1.5a Reciclaje exacto (pag. 70)
# ---------------------------------------------------------------

# Crear vector v con valores 2, 4, 6, 8
v <- 2 * 1:4

# Crear matriz A de 2x4 rellena con ceros
A <- matrix(0, 2, 4)

# Sumar vector v a la matriz A con reciclaje
# R opera por columnas: col1 usa v[1] y v[2], col2 usa v[3] y v[4], etc.
v + A
#      [,1] [,2] [,3] [,4]
# [1,]    2    6    2    6
# [2,]    4    8    4    8

In [ ]:
# ---------------------------------------------------------------
# 2.1.5b Reciclaje NO exacto: emite advertencia (pag. 71)
# ---------------------------------------------------------------

# Caso donde la longitud de la matriz NO es multiplo de la longitud del vector
v <- 2 * 1:4

# Matriz de 2x3 (6 elementos) vs vector de longitud 4: no es multiplo exacto
A <- matrix(0, 2, 3)

# La operacion se ejecuta pero R emite una advertencia
v + A
#      [,1] [,2] [,3]
# [1,]    2    6    2
# [2,]    4    8    4

# Mensaje de aviso:
# In v + A :
#   longitud de objeto mayor no es multiplo de la longitud de uno menor

### 2.1.6. Producto y división escalar-vector (pág. 71-72)

Los operadores `*` y `/` entre un escalar y un vector actúan **elemento a elemento**.

In [ ]:
# ---------------------------------------------------------------
# 2.1.6 Producto y division escalar-vector (pag. 71-72)
# ---------------------------------------------------------------

# Multiplicar el escalar 2 por cada elemento del vector 1:4
2 * 1:4
# [1] 2 4 6 8

# Dividir el escalar 2 entre cada elemento del vector 1:4
2 / 1:4
# [1] 2.0000000 1.0000000 0.6666667 0.5000000

### 2.1.7. Producto elemento a elemento entre vectores (pág. 72)

El operador `*` entre dos vectores de **igual longitud** multiplica elemento a elemento (no es el producto escalar).

In [ ]:
# ---------------------------------------------------------------
# 2.1.7 Producto elemento a elemento entre vectores (pag. 72)
# ---------------------------------------------------------------

# Multiplicacion elemento a elemento: 1*1=1, 2*2=4, 3*3=9
1:3 * 1:3
# [1] 1 4 9

### 2.1.8. Producto elemento a elemento entre matrices - Hadamard (pág. 72-73)

El operador `*` entre matrices realiza el producto de Hadamard. `t(A)` calcula la transpuesta. **No confundir con el producto matricial** (`%*%`).

In [ ]:
# ---------------------------------------------------------------
# 2.1.8 Producto de Hadamard (pag. 72-73)
# ---------------------------------------------------------------

# Crear matriz A de 2x2 con valores 1 a 4
(A <- matrix(1:4, 2, 2))
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

# Multiplicar A por su transpuesta elemento a elemento
# t(A) transpone la matriz: las columnas se convierten en filas
A * t(A)
#      [,1] [,2]
# [1,]    1    6
# [2,]    6   16

### 2.1.9. Operador potencia aplicado a matrices (pág. 73)

El operador `^` en R aplica la potencia **elemento a elemento**.

In [ ]:
# ---------------------------------------------------------------
# 2.1.9 Potencia elemento a elemento (pag. 73)
# ---------------------------------------------------------------

# Crear matriz A de 2x2 con valores 1 a 4
(A <- matrix(1:4, 2, 2))
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

# Elevar cada elemento al cuadrado: 1^2=1, 2^2=4, 3^2=9, 4^2=16
A^2
#      [,1] [,2]
# [1,]    1    9
# [2,]    4   16

# Elevar cada elemento a si mismo: 1^1=1, 2^2=4, 3^3=27, 4^4=256
A^A
#      [,1] [,2]
# [1,]    1   27
# [2,]    4  256

### 2.1.10. Producto escalar entre dos vectores - dot product (pág. 73-74)

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i$$

En R se obtiene combinando `*` y `sum()`. Dos vectores **ortogonales** tienen producto escalar igual a cero.

In [ ]:
# ---------------------------------------------------------------
# 2.1.10a Producto escalar (pag. 73-74)
# ---------------------------------------------------------------

# Definir vectores a y b
a <- 1:3
b <- c(2, 5, 8)

# Producto escalar: 1*2 + 2*5 + 3*8 = 2 + 10 + 24 = 36
sum(a * b)
# [1] 36

In [ ]:
# ---------------------------------------------------------------
# 2.1.10b Ortogonalidad: producto escalar = 0 (pag. 74)
# ---------------------------------------------------------------

# Ejemplo de ortogonalidad: vectores perpendiculares
a <- c(1, 1)
b <- c(-1, 1)

# Producto escalar de vectores ortogonales = 0
sum(a * b)
# [1] 0

### 2.1.11. Norma euclidiana de un vector (pág. 74-75)

$$\|\mathbf{v}\| = \sqrt{v_1^2 + \cdots + v_n^2}$$

R no tiene una función predefinida para vectores, pero se puede crear con `function()`, `sqrt()` y `sum()`.

In [ ]:
# ---------------------------------------------------------------
# 2.1.11 Norma euclidiana (pag. 74-75)
# ---------------------------------------------------------------

# Definir funcion personalizada para calcular la norma euclidiana
# Parametro: x (vector numerico)
# Retorna: escalar con la norma del vector
norm.vec <- function(x) sqrt(sum(x * x))

# Probar con el vector (1,1): norma = sqrt(1^2 + 1^2) = sqrt(2) ~= 1.414214
a <- c(1, 1)
norm.vec(a)
# [1] 1.414214

### 2.1.12. Producto matricial con `%*%` (pág. 75-76)

El producto matricial entre A(n×m) y B(m×p) requiere que el número de columnas de A coincida con el número de filas de B. El resultado tiene dimensiones n×p.

In [ ]:
# ---------------------------------------------------------------
# 2.1.12 Producto matricial %*% (pag. 75-76)
# ---------------------------------------------------------------

# Crear matriz A de 2x2 con valores 1 a 4
(A <- matrix(1:4, 2, 2))
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

# Crear matriz B de 2x1 (vector columna) con valor 2
(B <- matrix(2, 2, 1))
#      [,1]
# [1,]    2
# [2,]    2

# Producto matricial A %*% B: resultado es 2x1
# Fila 1: 1*2 + 3*2 = 8
# Fila 2: 2*2 + 4*2 = 12
A %*% B
#      [,1]
# [1,]    8
# [2,]   12

### 2.1.13. Producto interior y exterior con `crossprod` y `%o%` (pág. 76-77)

- **Producto interior** (A^T B): `crossprod()` o `%*%` tras transponer. Resultado: escalar.
- **Producto exterior** (A B^T): `%o%`. Resultado: matriz de rango 1.

In [ ]:
# ---------------------------------------------------------------
# 2.1.13a Producto interior (pag. 76)
# ---------------------------------------------------------------

# Vector a = (1, 2, 3)
a <- 1:3

# Producto interior: a^T * a = 1^2 + 2^2 + 3^2 = 14
a %*% a
#      [,1]
# [1,]   14

# Equivalente con crossprod (mas eficiente computacionalmente)
crossprod(a, a)
#      [,1]
# [1,]   14

In [ ]:
# ---------------------------------------------------------------
# 2.1.13b Producto exterior (pag. 77)
# resultado[i,j] = a[i] * a[j]
# ---------------------------------------------------------------
a <- 1:3
a %o% a
#      [,1] [,2] [,3]
# [1,]    1    2    3
# [2,]    2    4    6
# [3,]    3    6    9

### 2.1.14. Producto de Kronecker (pág. 77-79)

El producto de Kronecker (A ⊗ B) entre A(m×n) y B(p×q) produce una matriz en bloques de dimensión (mp)×(nq), donde cada elemento de A multiplica toda la matriz B. En R: `kronecker(A, B)`.

In [ ]:
# ---------------------------------------------------------------
# 2.1.14 Producto de Kronecker (pag. 77-79)
# ---------------------------------------------------------------

# Crear matriz A de 1x3 rellena con 1s
(A <- matrix(1, 1, 3))
#      [,1] [,2] [,3]
# [1,]    1    1    1

# Crear matriz B de 2x2 con valores 1 a 4
(B <- matrix(1:4, 2, 2))
#      [,1] [,2]
# [1,]    1    3
# [2,]    2    4

# Producto de Kronecker A (x) B
# Cada elemento de A (=1) multiplica toda B
# Resultado: matriz de dimension (1*2) x (3*2) = 2x6
kronecker(A, B)
#      [,1] [,2] [,3] [,4] [,5] [,6]
# [1,]    1    3    1    3    1    3
# [2,]    2    4    2    4    2    4

---
## 2.2. Ecuaciones algebraicas: raíces de polinomios (pág. 79-80)

### Conceptos clave
`polyroot()` recibe un vector con los **coeficientes en orden creciente de grado** (término independiente primero) y devuelve las raíces en notación compleja `a+bi`.

In [ ]:
# ---------------------------------------------------------------
# 2.2 Ecuaciones algebraicas: polyroot() (pag. 79-80)
# ---------------------------------------------------------------

# Resolver: 2x^2 + 5x + 5 = x^2 + 3x + 4  ->  x^2 + 2x + 1 = 0
# Coeficientes de p1 y p2 en orden creciente de grado
p1 <- c(5, 5, 2)   # coef. de 2x^2 + 5x + 5
p2 <- c(4, 3, 1)   # coef. de x^2 + 3x + 4

# polyroot devuelve raices en forma compleja
# Solucion: x = -1 (raiz doble)
polyroot(p1 - p2)
# [1] -1-0i -1+0i

---
## 2.3. Sistemas de ecuaciones lineales con `solve()` (pág. 80-82)

### Conceptos clave
Un sistema Ax = b se resuelve con `solve(A, b)`, que calcula x = A⁻¹b. Se construye A con `rbind()` (unir filas).

**Sistema:** 3x + y + 2z = 10 ; 4x + 3y + 4z = 21 ; 2x + y + 2z = 9

In [ ]:
# ---------------------------------------------------------------
# 2.3 Sistemas de ecuaciones lineales: solve() (pag. 80-82)
# ---------------------------------------------------------------

# Definir cada ecuacion como vector de coeficientes
e1 <- c(3, 1, 2)   # coef. ecuacion 1
e2 <- c(4, 3, 4)   # coef. ecuacion 2
e3 <- c(2, 1, 2)   # coef. ecuacion 3

# Construir la matriz de coeficientes A uniendo filas con rbind()
A <- rbind(e1, e2, e3)

# Vector de terminos independientes
b <- c(10, 21, 9)

# Resolver: x = A^{-1} * b
# Solucion: x=1, y=3, z=2
solve(A, b)
# [1] 1 3 2

---
## 2.4. Descomposición matricial

### 2.4.1. Valores y vectores propios con `eigen()` (pág. 82-84)

La **descomposición espectral** factoriza A en sus valores propios (λ) y vectores propios (v) tal que Av = λv. `eigen()` devuelve una lista con `$values` y `$vectors`.

In [ ]:
# ---------------------------------------------------------------
# 2.4.1 Valores y vectores propios: eigen() (pag. 82-84)
# ---------------------------------------------------------------

# Crear matriz diagonal A = [[2,0],[0,2]]
A <- matrix(c(2, 0, 0, 2), 2, 2)

# Calcular valores y vectores propios
eigen(A)

# $values: valores propios lambda1=2, lambda2=2
# [1] 2 2

# $vectors: columnas = vectores propios asociados
#      [,1] [,2]
# [1,]    0   -1
# [2,]    1    0

### 2.4.2. Descomposición en valores singulares - SVD (pág. 84-85)

La **SVD** factoriza cualquier matriz A como A = UDVᵀ, donde U y V son ortogonales y D es diagonal con los **valores singulares**. En R: `svd()` devuelve `$d`, `$u` y `$v`.

In [ ]:
# ---------------------------------------------------------------
# 2.4.2 Descomposicion en valores singulares: svd() (pag. 84-85)
# ---------------------------------------------------------------

# Reutilizar matriz diagonal A = [[2,0],[0,2]]
A <- matrix(c(2, 0, 0, 2), 2, 2)

# Descomposicion en valores singulares
svd(A)

# $d: valores singulares (diagonal de D)
# [1] 2 2

# $u: matriz ortogonal U
#      [,1] [,2]
# [1,]    1    0
# [2,]    0    1

# $v: matriz ortogonal V
#      [,1] [,2]
# [1,]    1    0
# [2,]    0    1

---
# 3. Funciones (pág. 85-95)
## 3.1. Clases de funciones

### 3.1.1. Definición y evaluación de funciones matemáticas (pág. 86-87)

En R, las funciones se definen con `function(args) expr`. Gracias a la vectorización nativa, se pueden evaluar para escalares o vectores completos sin bucles.

In [ ]:
# ---------------------------------------------------------------
# 3.1.1 Definicion y evaluacion de funciones (pag. 86-87)
# ---------------------------------------------------------------

# Definir funcion de una variable: y = x^2 - 3
y <- function(x) x^2 - 3

# Evaluar en x = 1: resultado = 1 - 3 = -2
y(1)
# [1] -2

# Crear vector de valores iniciales del -3 al 3
(x0 <- -3:3)
# [1] -3 -2 -1  0  1  2  3

# Evaluar y en todos los puntos (vectorizacion automatica)
y(x0)
# [1]  6  1 -2 -3 -2  1  6

In [ ]:
# ---------------------------------------------------------------
# 3.1.1 Funcion de dos variables (pag. 87)
# ---------------------------------------------------------------

# Definir funcion de dos variables: y = x1^2 + x2^2
y <- function(x1, x2) x1^2 + x2^2

### 3.1.2. Búsqueda de raíces con `uniroot()` (pág. 87)

`uniroot()` busca el valor de x donde f(x) = 0 dentro de un intervalo. El intervalo debe contener **exactamente una raíz** (la función debe cambiar de signo en los extremos).

In [ ]:
# ---------------------------------------------------------------
# 3.1.2 Busqueda de raices: uniroot() (pag. 87)
# ---------------------------------------------------------------

# Redefinir y = x^2 - 3 para este ejemplo
y <- function(x) x^2 - 3

# Buscar raiz en el intervalo [-2, 0]
# La raiz negativa de sqrt(3) ~= -1.73205 esta en ese intervalo
uniroot(y, c(-2, 0))
# $root        -> valor de x donde f(x) ~= 0
# [1] -1.73205

# $f.root      -> valor de f en la raiz (debe ser ~= 0)
# [1] -3.278749e-06

# $iter        -> numero de iteraciones
# [1] 5

# $estim.prec  -> precision estimada
# [1] 6.103516e-05

In [ ]:
# ---------------------------------------------------------------
# 3.1.2 uniroot() con intervalo invalido (pag. 87)
# ---------------------------------------------------------------

# Intervalo [-2, 2] contiene DOS raices: genera error
# f() values at end points not of opposite sign
# uniroot(y, c(-2, 2))
# (linea comentada para no interrumpir la ejecucion del notebook)

## 3.2. Representación gráfica

### 3.2.1. Gráfico de una función con `plot()` (pág. 87-90)

`plot()` acepta directamente una función de una variable. Parámetros clave: `main`, `xlab`, `ylab`, `xlim`, `ylim`, `type` (`"l"` = línea, `"p"` = puntos), `lwd` (grosor).

In [ ]:
# ---------------------------------------------------------------
# 3.2.1 Graficar una funcion con plot() (pag. 87-90)
# ---------------------------------------------------------------

# Definir funcion y = x * sqrt(x + 3)
y <- function(x) x * sqrt(x + 3)

# Graficar con parametros personalizados
plot(y,
     main = "Titulo del grafico",            # titulo
     xlab = "Rotulo del eje de abscisas",     # etiqueta eje x
     ylab = "Rotulo del eje de ordenadas",    # etiqueta eje y
     xlim = c(-4, 2),                         # rango eje x
     ylim = c(-2, 1),                         # rango eje y
     type = "l",                              # tipo: linea continua
     lwd = 5)                                 # grosor de linea

# Warning: NaNs produced (valores fuera del dominio [-3,inf) generan NaN)

### 3.2.2. Gráficos de varias funciones con `lines()` y `legend()` (pág. 90-92)

Para superponer múltiples funciones: primero se crea el **marco vacío** con `type="n"` y luego se añaden curvas con `lines()`. La leyenda se agrega con `legend()`.

In [ ]:
# ---------------------------------------------------------------
# 3.2.2 Varias funciones con lines() y legend() (pag. 90-92)
# ---------------------------------------------------------------

# Vector de 1001 puntos en [-5, 5] con paso 0.01
x0 <- seq(-5, 5, 0.01)

# Longitud del vector
(lon <- length(x0))
# [1] 1001

# Evaluar las tres funciones trigonometricas en x0
y1 <- sin(x0)   # seno
y2 <- cos(x0)   # coseno
y3 <- tan(x0)   # tangente

# Definir rangos de los ejes
(xrange <- c(1, lon))    # indices del vector como eje x
(yrange <- c(-4, 4))     # rango vertical

# Crear marco vacio: type="n" no dibuja datos
# xaxt="n" elimina el eje x por defecto (se aniade personalizado)
plot(xrange, yrange, type = "n", xaxt = "n", xlab = "",
     ylab = "")

# Aniadir las tres curvas al grafico
lines(y1, type = "p", lwd = 1, col = "grey")    # seno en gris
lines(y2, type = "p", lwd = 1, col = "snow4")   # coseno en snow4
lines(y3, type = "p", lwd = 1, col = "black")   # tangente en negro

# Linea horizontal en y=0
abline(h = 0, lwd = 2)

# Leyenda en esquina inferior izquierda
legend("bottomleft",
       c("sin(x)", "cos(x)", "tan(x)"),
       fill = c("grey", "snow4", "black"),
       cex = 1.5)

### 3.2.3. Función definida a trozos con `for` e `if/else` (pág. 92-93)

Para funciones por partes se usa un bucle `for` con condicionales `if/else if/else`. El símbolo `&` representa la intersección lógica.

f(x) = 2 si x < -2 ; x² - 4 si -2 ≤ x < 3 ; 8 - x si x ≥ 3

In [ ]:
# ---------------------------------------------------------------
# 3.2.3 Funcion definida a trozos: for + if/else (pag. 92-93)
# ---------------------------------------------------------------

# Dominio: vector de x en (-5, 5)
x0 <- (-5:5)

# Numero total de puntos
n <- length(x0)

# Inicializar vector y con n ceros
y <- rep(0, n)

# Asignar valor de y segun la region de x
for (i in 1:n) {
  x <- x0[i]              # tomar el i-esimo valor de x

  if (x < -2) {
    y[i] <- 2             # primer tramo: constante 2
  } else if (x >= -2 & x < 3) {
    y[i] <- x * x - 4    # segundo tramo: parabola desplazada
  } else {
    y[i] <- 8 - x         # tercer tramo: funcion lineal decreciente
  }
}

# Graficar la funcion definida a trozos
plot(y, type = "l", lwd = 6)

### 3.2.4. Gráficos 3D con `outer()` y `persp()` (pág. 93-95)

Para graficar z = f(x, y): `outer()` evalúa f en una grilla de puntos generando una matriz, y `persp()` renderiza la superficie 3D.

**Ejemplo:** paraboloide hiperbólico z = x² - y² (punto de silla, Figura II.4).

In [ ]:
# ---------------------------------------------------------------
# 3.2.4 Graficos 3D: outer() y persp() (pag. 93-95)
# ---------------------------------------------------------------

# Definir dominio en x e y de -100 a 100
x0 <- -100:100
y0 <- -100:100

# Definir funcion de dos variables z = x^2 - y^2
z <- function(x, y) x * x - y * y

# outer() evalua z en todas las combinaciones (xi, yj)
# resultado: matriz de 201x201 con todos los valores de z
f <- outer(x0, y0, z)

# Graficar la superficie tridimensional
persp(f)

---
# 4. Cálculo diferencial e integral (pág. 95-114)
## 4.1. Aproximación a la derivada

### 4.1.1. Derivada simbólica con `D()` y numérica por diferencias finitas (pág. 96-100)

`D(expression(...), "var")` calcula la derivada simbólica. Para derivadas numéricas se aplica la fórmula de diferencia hacia adelante:

f'(t₀) ≈ [f(t₀ + Δt) - f(t₀)] / Δt

**Ejemplo (Galileo):** caída libre desde la Torre de Pisa, s(t) = 4.9·t²

In [ ]:
# ---------------------------------------------------------------
# 4.1.1a Derivada simbolica: D() (pag. 96-98)
# ---------------------------------------------------------------

# Definir la funcion de caida libre s(t) = 4.9 * t^2
s <- function(t) 4.9 * t^2

# Calcular la derivada simbolica de 4.9t^2 con respecto a t
# Resultado esperado: 4.9 * (2 * t) = 9.8t
D(expression(4.9 * t^2), "t")
# 4.9 * (2 * t)

In [ ]:
# ---------------------------------------------------------------
# 4.1.1b Derivada numerica por diferencias finitas (pag. 98-100)
# ---------------------------------------------------------------

# Aproximacion numerica de s'(t) en t0=2 con dt suficientemente pequenio
dt <- 0.0001   # diferencial muy pequenio
t0 <- 2        # punto de evaluacion

# Formula de diferencia hacia adelante: [s(t0+dt) - s(t0)] / dt
(s(t0 + dt) - s(t0)) / dt
# [1] 19.60049   -> velocidad ~= 19.6 m/s en t=2 s

### 4.1.2. Derivada numérica en dominio completo y visualización (pág. 100-102)

Para obtener la función derivada empírica en todo el dominio, se calcula el vector de **diferencias consecutivas** de s(t) y se divide entre dt.

In [ ]:
# ---------------------------------------------------------------
# 4.1.2 Derivada numerica en todo el dominio (pag. 100-102)
# ---------------------------------------------------------------

# Redefinir s(t) y calcular T (tiempo de caida desde 56 m)
s <- function(t) 4.9 * t^2

# Calcular tiempo total T: 56 = 4.9*T^2 -> T = sqrt(56/4.9) ~= 3.38 s
T <- uniroot(function(t) 4.9 * t^2 - 56,
             c(0, 5))$root

# Parametros de la aproximacion numerica
dt <- 0.01
t.0 <- seq(0, 3.38, by = dt)    # vector de tiempos
n <- length(t.0)                  # numero de puntos

# Evaluar s(t) en todos los puntos del dominio
f.s <- s(t.0)

# Incrementos consecutivos: s(t+dt) - s(t)
# Produce vector de longitud n-1
inc.s <- f.s[2:n] - f.s[1:(n - 1)]

# Dividir entre dt -> derivada numerica (velocidad en cada punto)
ds.dt <- inc.s / dt

# Rangos para los ejes
xrange <- c(1, n)
yrange <- c(0, max(f.s))

# Crear marco del grafico con etiquetas de tiempo reales
plot(xrange, yrange, type = 'n', xaxt = 'n',
     xlab = 'Tiempo (t)', ylab = 'Distancia (s)')

# Definir marcas del eje x cada 50 puntos
lab = 1 + 50 * 0:6
axis(1, at = lab, labels = t.0[lab])

# Graficar s(t) en negro y ds/dt (velocidad) en snow4
lines(f.s, type = 'l', lwd = 4, col = 'black')
lines(ds.dt, type = 'l', lwd = 4, col = 'snow4')

# Leyenda
legend('bottomright', c('s(t)', 'ds/dt'),
       fill = c('black', 'snow4'), cex = 1.5)

---
## 4.2. Integración: suma de Riemann e `integrate()` (pág. 103-108)

### Conceptos clave
La **suma de Riemann** aproxima el área bajo una curva:

S = Σ v(tⱼ)·Δt  →  (cuando Δt→0) ∫ᵃᵇ v(t) dt

**Ejemplo:** velocidad de un paracaidista v(t) = 54·tanh(9.81t/54)

In [ ]:
# ---------------------------------------------------------------
# 4.2a Funcion de velocidad del paracaidista (pag. 103-104)
# v_inf = 54 m/s (velocidad terminal), g = 9.81 m/s^2
# ---------------------------------------------------------------
f.v <- function(t) 54 * tanh(9.81 * t / 54)

# Graficar v(t) en el intervalo [0, 20]
plot(f.v, xlim = c(0, 20), lwd = 4, col = 'magenta',
     xlab = 'Tiempo (t)', ylab = 'Velocidad (v)')

In [ ]:
# ---------------------------------------------------------------
# 4.2b Funcion propia de integracion por suma de Riemann (pag. 104-106)
# Parametros:
#   fun: funcion a integrar
#   a:   limite inferior
#   b:   limite superior
#   dt:  ancho del subintervalo (paso)
# Retorna: aproximacion del area bajo la curva
# ---------------------------------------------------------------
int.riemann <- function(fun, a, b, dt) {
  t.0 <- seq(a, b, by = dt)    # puntos de evaluacion
  f.0 <- fun(t.0)              # valores de la funcion en esos puntos
  suma <- sum(f.0 * dt)        # suma de Riemann: suma f(tj)*dt
  return(suma)
}

In [ ]:
# ---------------------------------------------------------------
# 4.2c Convergencia de la suma de Riemann vs integrate() (pag. 106-108)
# ---------------------------------------------------------------

# Evaluar con diferentes pasos dt (convergencia hacia el valor exacto)
int.riemann(f.v, 0, 10, 2)      # dt=2 -> baja precision
# [1] 389.9774

int.riemann(f.v, 0, 10, 1)      # dt=1
# [1] 366.5903

int.riemann(f.v, 0, 10, 0.1)   # dt=0.1
# [1] 344.2708

int.riemann(f.v, 0, 10, 0.01)  # dt=0.01
# [1] 341.9732

int.riemann(f.v, 0, 10, 0.001) # dt=0.001 -> alta precision
# [1] 341.7428

# Comparar con integrate() de R base (cuadratura adaptativa)
integrate(f.v, 0, 10)
# 341.7172 with absolute error < 3.8e-12

### Aceleración: retomando la derivada de v(t) con `D()` (pág. 108)

Cierre del ejemplo del paracaidista: `D()` calcula la expresión simbólica de la derivada de v(t); el resultado se define como función R para evaluarla numéricamente y compararla con la velocidad.

In [ ]:
# ---------------------------------------------------------------
# 4.1.3 Aceleracion: derivada simbolica de v(t) (pag. 108)
# ---------------------------------------------------------------

# Calcular la derivada simbolica de v(t) con respecto a t
D(expression(54 * tanh(9.81 * t / 54)), "t")
# 54 * (9.81/54/cosh(9.81 * t/54)^2)

# Definir funcion de aceleracion a(t) = v'(t)
f.a <- function(t) 54 * (9.81 / 54 / cosh(9.81 * t /
  54)^2)

# Graficar velocidad y aceleracion en t entre 0 y 20
t.0 <- 0:20

# Graficar v(t) en negro como linea base
plot(f.v(t.0), type = 'l', lwd = 4, col = 'black',
     xlab = 'Tiempo (t)', ylab = '')

# Superponer a(t) en color slate gray
lines(f.a(t.0), lwd = 4, col = 'slategray')

# Leyenda descriptiva
legend('right', c('Velocidad (v(t))',
                  'Aceleracion (dv/dt)'), fill = c('black',
                                                    'slategray'), cex = 1.5)

---
## 4.3. Ecuaciones diferenciales con `deSolve` (pág. 109-113)

### Conceptos clave
El paquete `deSolve` resuelve EDOs con condiciones iniciales mediante `ode()`. La EDO se formula como función con argumentos `(tiempo, cond.ini, parametros)` y el *output* debe ser una lista.

**Modelo de aprendizaje:** dY/dt = k(M - Y), Y(0)=0, k=0.02, M=10

In [ ]:
# ---------------------------------------------------------------
# 4.3a Instalar y cargar deSolve (pag. 109-110)
# ---------------------------------------------------------------

# Instalar deSolve si no esta disponible (necesario en Colab)
if (!require(deSolve)) install.packages("deSolve")

# Cargar el paquete
library(deSolve)

In [ ]:
# ---------------------------------------------------------------
# 4.3b Parametros y condicion inicial (pag. 110)
# ---------------------------------------------------------------

# Definir parametros del modelo
# k: tasa de aprendizaje, M: nivel maximo alcanzable
parametros <- c(k = 0.02, M = 10)

# Condicion inicial: al inicio el estudiante no sabe nada (Y=0)
cond.ini <- c(Y = 0)

# Dominio temporal: de 0 a 365 dias
tiempo <- 0:365

In [ ]:
# ---------------------------------------------------------------
# 4.3c Definir y resolver la EDO con ode() (pag. 110-112)
# ---------------------------------------------------------------

# Definir la EDO como funcion con estructura requerida por deSolve
# Argumentos obligatorios: t (tiempo), cond.ini, parametros
# El output DEBE ser una lista (requisito de deSolve)
f.apren <- function(t, cond.ini,
                    parametros) {
  with(as.list(c(cond.ini, parametros)), {
    dY <- k * (M - Y)      # ecuacion diferencial: tasa de cambio
    return(list(dY))        # output como lista
  })
}

# Resolver la EDO numericamente
# Retorna matriz con columnas: time y Y
sol <- ode(cond.ini, tiempo, f.apren, parametros)

# Ver primeras filas: aprendizaje rapido al inicio
head(sol)
#      time          Y
# [1,]    0 0.0000000
# [2,]    1 0.1980142
# ...

# Ver ultimas filas: Y converge al limite M=10
tail(sol)
#        time        Y
# [361,]  360 9.992534
# ...
# [366,]  365 9.993245

In [ ]:
# ---------------------------------------------------------------
# 4.3d Graficar la curva de aprendizaje (pag. 112-113)
# ---------------------------------------------------------------
plot(sol,
     xlab = "tiempo (t)",
     ylab = "Aprendizaje (Y)",
     lwd = 4,
     col = "red",
     main = "Curva de aprendizaje")

---
# 5. Optimización con `optimize()` y `optim()` (pág. 114-117)

### Conceptos clave
- `optimize()`: mínimo/máximo de función de **una variable** en intervalo dado.
- `optim()`: optimización de funciones de **múltiples variables**, requiere valores iniciales.

In [ ]:
# ---------------------------------------------------------------
# 5a optimize(): funcion de una variable (pag. 114-116)
# ---------------------------------------------------------------

# Definir funcion: y = 3*sin(3x)
f1 <- function(x) 3 * sin(3 * x)

# Graficar en dominio [-1, 1]
plot(f1, from = -1, to = 1, lwd = 4)
title("Funcion y=3sin(3x) en el dominio [-1,1]"
  )

# Encontrar el MINIMO en [-1, 1]
optimize(f1, c(-1, 1))
# $minimum: coordenada x del minimo
# [1] -0.5235812
# $objective: valor de f en el minimo
# [1] -3

# Encontrar el MAXIMO (maximum=TRUE)
optimize(f1, c(-1, 1), maximum = TRUE)
# $maximum
# [1] 0.5235812
# $objective
# [1] 3

In [ ]:
# ---------------------------------------------------------------
# 5b optim(): funcion de dos variables (pag. 116-117)
# ---------------------------------------------------------------

# Optimizacion de funcion de dos variables: y = 2x1^2 + 2x2^2 - 4
# Los dos argumentos se pasan como un unico vector x
f.y <- function(x) {
  x1 <- x[1]                  # extraer primera variable
  x2 <- x[2]                  # extraer segunda variable
  2 * x1^2 + 2 * x2^2 - 4    # evaluar funcion objetivo
}

# Llamar a optim() con valores iniciales x1*=-1, x2*=1.5
# optim() usa Nelder-Mead por defecto para problemas sin restricciones
optim(c(-1, 1.5), f.y)

# $par: parametros en el minimo (~= 0, 0)
# [1]  9.038020e-05 -4.059674e-05

# $value: valor de y en el minimo = -4
# [1] -4

# $counts: evaluaciones de funcion y gradiente
# function gradient
#       69        NA

# $convergence: 0 = convergencia exitosa
# [1] 0

---
# 6. Análisis de variable compleja (pág. 117-122)

### 6.1. Raíces complejas de polinomios y operaciones básicas (pág. 117-121)

R trabaja nativamente con números complejos en notación `a+bi`. Funciones útiles: `Re()`, `Im()`, `Conj()`, `Mod()`, `Arg()`.

In [ ]:
# ---------------------------------------------------------------
# 6.1a Raices complejas de un polinomio: polyroot() (pag. 117-118)
# ---------------------------------------------------------------

# Resolver x^2 - 10x + 40 = 0 (raices complejas conjugadas)
# Coeficientes en orden creciente de grado: (40, -10, 1)
polyroot(c(40, -10, 1))
# [1] 5+3.872983i  5-3.872983i

In [ ]:
# ---------------------------------------------------------------
# 6.1b Introducir numeros complejos: Re() e Im() (pag. 118-119)
# ---------------------------------------------------------------

# Introducir z = 10 - 5i de dos formas equivalentes
(z <- 10 - 5i)
# [1] 10-5i

(z <- complex(real = 10, imaginary = -5))
# [1] 10-5i

# Extraer parte real e imaginaria
Re(z)   # [1] 10
Im(z)   # [1] -5

In [ ]:
# ---------------------------------------------------------------
# 6.1c Operaciones algebraicas con complejos (pag. 119-120)
# ---------------------------------------------------------------

# Operaciones algebraicas con numeros complejos
z1 <- -5 + 1i
z2 <- -10 + 4i

# Suma: partes reales e imaginarias por separado
z1 + z2
# [1] 15+5i

# Resta
z1 - z2
# [1] -5-3i

# Multiplicacion por escalar real
5 * z1
# [1] 25+5i

# Multiplicacion de dos complejos (propiedad distributiva, i^2=-1)
z1 * z2
# [1] 46+30i

# Division (equivale a multiplicar por conjugado del denominador)
z1 / z2
# [1] 0.4655172-0.0862069i

In [ ]:
# ---------------------------------------------------------------
# 6.1d Conjugado de un numero complejo: Conj() (pag. 120-121)
# ---------------------------------------------------------------

# Conjugado de un numero complejo (cambia signo de parte imaginaria)
(z3 <- -4 + 2i)
# [1] -4+2i

(z4 <- Conj(z3))   # conjugado de z3
# [1] -4-2i

# Producto de z3 por su conjugado: siempre resulta numero real
z3 * z4
# [1] 20+0i

### 6.2. Raíces complejas n-ésimas (pág. 121-122)

Usando la ecuación de Euler, cualquier número tiene exactamente **n raíces complejas** de orden n:

z = ⁿ√r · e^((θ/n + 2πk/n)i),  k = 0, 1, ..., n-1

In [ ]:
# ---------------------------------------------------------------
# 6.2a Funcion propia para raices complejas n-esimas (pag. 121-122)
# Parametros:
#   r: numero del que se calculan las raices
#   n: orden de la raiz
# Retorna: vector de n numeros complejos con las raices
# ---------------------------------------------------------------
raiz.comp <- function(r, n) {
  sol <- array(data = NA, dim = n)   # inicializar vector de resultados NA

  m1 <- (abs(r)^(1/n))              # modulo de todas las raices = |r|^(1/n)

  for (j in 0:n - 1) {
    if (r < 0) {
      m2 <- (pi/n) + 2 * j * (pi/n) # argumento para r negativo
    } else {
      m2 <- 2 * j * (pi/n)           # argumento para r positivo
    }

    # Calcular raiz en forma binomica: m1 * e^(im2) = m1*(cos(m2)+i*sin(m2))
    sol[j + 1] <- m1 * complex(real = cos(m2),
                                imaginary = sin(m2))
  }

  return(sol)   # vector con las n raices
}

In [ ]:
# ---------------------------------------------------------------
# 6.2b Verificacion de raiz.comp() (pag. 122)
# ---------------------------------------------------------------

# Verificar: raices cuadradas de 9 son 3 y -3
raiz.comp(9, 2)
# [1]  3+0i -3+0i

# Calcular las tres raices cubicas de 90
raiz.comp(90, 3)
# [1]  4.481405+0.00000i -2.240702+3.88101i
#     -2.240702-3.88101i

---
## Conclusión

Este notebook cubre la totalidad del código R del **Capítulo II** de Liviano & Pujol (2017), siguiendo el mismo orden y numeración de secciones que el texto original.

| Sección del libro | Tema | Funciones clave |
|---|---|---|
| 2.1 | Operaciones algebraicas | `+`, `-`, `*`, `/`, `^`, `sum()`, `%*%`, `%o%`, `crossprod()`, `kronecker()`, `t()` |
| 2.2 | Ecuaciones algebraicas | `polyroot()` |
| 2.3 | Sistemas de ecuaciones lineales | `solve()`, `rbind()` |
| 2.4 | Descomposición matricial | `eigen()`, `svd()` |
| 3.1 | Clases de funciones | `function()`, `uniroot()` |
| 3.2 | Representación gráfica | `plot()`, `lines()`, `legend()`, `persp()`, `outer()` |
| 4.1 | Aproximación a la derivada | `D()`, diferencias finitas |
| 4.2 | Integración | `integrate()`, suma de Riemann |
| 4.3 | Ecuaciones diferenciales | `deSolve::ode()` |
| 5 | Optimización | `optimize()`, `optim()` |
| 6 | Análisis de variable compleja | `Re()`, `Im()`, `Conj()`, `complex()` |

### Cómo ejecutar
1. Abrir en **Jupyter Lab**, **VS Code** o **Google Colab** con kernel `R`.
2. Ejecutar las celdas en orden: varias reutilizan objetos (`A`, `B`, `f.v`, `t.0`...) creados en celdas anteriores.
3. La sección 4.3 requiere el paquete `deSolve` (se instala automáticamente si falta).

---
*Notebook estandarizado a partir del PDF oficial del capítulo (Cap02_Algebra_Lineal_Calculo_R.pdf).*
*Referencia: Liviano Solís, D. & Pujol Jover, M. (2017). Análisis cuantitativo con R: matemáticas, estadística y econometría. Editorial UOC.*